TorontoRoonRentals/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TorontoRoonRentals.Models
{
    public partial class Room
    {
        public Room()
        {
            Appliances = new HashSet<Appliances>();
            Description = new HashSet<Description>();
            RoomImages = new HashSet<RoomImages>();
            Utilities = new HashSet<Utilities>();
        }

        public int RoomId { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public decimal Price { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
        [DataType(DataType.Date)]
        public DateTime Moveindate { get; set; }
        public DateTime CreatedDate { get; set; }
        public int Bathrooms { get; set; }
        public bool IsParking { get; set; }
        public bool IsPetFriendly { get; set; }
        public bool IsSmoking { get; set; }
        public int? Type { get; set; }

        public AspNetUsers User { get; set; }
        public ICollection<Appliances> Appliances { get; set; }
        public ICollection<Description> Description { get; set; }
        public ICollection<RoomImages> RoomImages { get; set; }
        public ICollection<Utilities> Utilities { get; set; }
    }
}

TorontoRoonRentals/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TorontoRoonRentals.Data;
using TorontoRoonRentals.Models;
using TorontoRoonRentals.ViewModels;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using System.IO;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using TorontoRoonRentals.Common;

namespace TorontoRoonRentals.Controllers
{
    [Authorize]
    public class RoomController : Controller
    {
        TorontoRoomRentalsContext db = new TorontoRoomRentalsContext();
        
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult PostRoom()
        {
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        async public Task<IActionResult> PostRoom(RoomVM roomVM)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    AzureConnection azureConnection = new AzureConnection();

                    roomVM.Room.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    roomVM.Room.CreatedDate = DateTime.Now;

                    db.Room.Add(roomVM.Room);
                    await db.SaveChangesAsync();

                    roomVM.Utilities.RoomId = roomVM.Room.RoomId;
                    roomVM.Appliances.RoomId = roomVM.Room.RoomId;
                    roomVM.Description.RoomId = roomVM.Room.RoomId;

                    db.Utilities.Add(roomVM.Utilities);
                    db.Appliances.Add(roomVM.Appliances);
                    db.Description.Add(roomVM.Description);


                    foreach (var image in roomVM.Images)
                    {
                        if (image.Length > 0)
                        {
                            RoomImages roomImage = new RoomImages();

                            string url = "https://sqlvamstj45g4qye7y.blob.core.windows.net/images";
                            string extension = Path.GetExtension(image.FileName);
                            string year = DateTime.Now.Year.ToString();
                            string month = DateTime.Now.Month.ToString();
                            string day = DateTime.Now.Day.ToString();
                            string nowTime = DateTime.Now.ToString("yymmssffff");

                            string path = $@"{year}\{month}\{day}\{roomVM.Room.RoomId}\";
                            string fileName = User.FindFirst(ClaimTypes.NameIdentifier).Value + nowTime + extension;
                            string imagePathAndFileName = path + fileName;
                           
                            using(var memoryStream = new MemoryStream())
                            {
                                await image.CopyToAsync(memoryStream);
                                memoryStream.Position = 0;
                                await azureConnection.UploadImageMemoryStream(imagePathAndFileName, memoryStream);
                            }

                            var imageUrlPath = $@"{url}/{year}/{month}/{day}/{roomVM.Room.RoomId}/{fileName}";
                            roomImage.RoomId = roomVM.Room.RoomId;
                            roomImage.ImagePath = imageUrlPath;
                            roomVM.RoomImages.Add(roomImage);
                        }
                    }

                    await db.RoomImages.AddRangeAsync(roomVM.RoomImages);
                    await db.SaveChangesAsync();

                    return RedirectToAction("RoomDetail", new { id = roomVM.Room.RoomId });
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

 
        [HttpGet]
     public async Task<IActionResult> RoomEdit(int? id)
        {
            try
            {
                if (id == null)
                    return StatusCode(500);
                var room = db.Room.Find(id);

                if (room == null)
                    return StatusCode(404);

                if (room.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value)
                {
                    var utility = db.Utilities.Where(u => u.RoomId == room.RoomId).FirstOrDefault();
                    var appliance = db.Appliances.Where(a => a.RoomId == room.RoomId).FirstOrDefault();
                    var description = db.Description.Where(d => d.RoomId == room.RoomId).FirstOrDefault();
                    RoomVM roomVM = new RoomVM
                    {
                        Room = room,
                        Utilities = utility,
                        Appliances = appliance,
                        Description = description
                    };
                    TempData["roomID"] = room.RoomId;
                    return View(roomVM);
                }
                return RedirectToAction("Index");
            }
            catch (Exception )
            {

                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> RoomEdit(RoomVM roomVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int roomId = (int)TempData["roomID"];
                    Room room = await db.Room.FindAsync(roomId);

                    if (room == null)
                        return StatusCode(404);

                    if (room.UserId == User.FindFirst(ClaimTypes.NameIdentifier).Value)
                    {
                        Utilities utility = db.Utilities.Where(u => u.RoomId == room.RoomId).FirstOrDefault();
                        Appliances appliance = db.Appliances.Where(a => a.RoomId == room.RoomId).FirstOrDefault();
                        Description description = db.Description.Where(d => d.RoomId == room.RoomId).FirstOrDefault();

                        roomVM.Room.RoomId = room.RoomId;
                        roomVM.Room.UserId = room.UserId;
                        roomVM.Room.CreatedDate = DateTime.Now;
                        roomVM.Utilities.RoomId = utility.RoomId;
                        roomVM.Utilities.UtilityId = utility.UtilityId;
                        roomVM.Appliances.RoomId = appliance.RoomId;
                        roomVM.Appliances.ApplianceId = appliance.ApplianceId;
                        roomVM.Description.RoomId = description.RoomId;
                        roomVM.Description.DescriptionId = description.DescriptionId;

                        db.Entry(room).CurrentValues.SetValues(roomVM.Room);
                        db.Entry(utility).CurrentValues.SetValues(roomVM.Utilities);
                        db.Entry(appliance).CurrentValues.SetValues(roomVM.Appliances);
                        db.Entry(description).CurrentValues.SetValues(roomVM.Description);

                        await db.SaveChangesAsync();
                        return RedirectToAction("RoomDetail", new { id = roomVM.Room.RoomId });
                    }
                }
                catch (Exception )
                {
                    return View();
                }
            }
            return View();
      
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> RoomDetail(int? id)
        {
            if (id == null)
                return StatusCode(500);
            var room = await db.Room.FindAsync(id);
            var utility = db.Utilities.Where(u => u.RoomId == room.RoomId).FirstOrDefault();
            var appliance = db.Appliances.Where(a => a.RoomId == room.RoomId).FirstOrDefault();
            var description = db.Description.Where(d => d.RoomId == room.RoomId).FirstOrDefault();
            var roomImages = db.RoomImages.Where(i => i.RoomId == room.RoomId);
            if (room == null)
                return StatusCode(404);

            RoomVM roomVM = new RoomVM
            {
                Room = room,
                Utilities = utility,
                Appliances = appliance,
                Description = description
            };
            foreach (var image in roomImages)
            {
                roomVM.RoomImages.Add(image);
            }
            TempData["lat"] = room.Lat;
            TempData["lng"] = room.Lng;
            return View(roomVM);

        }

        [AllowAnonymous]
        public IActionResult RoomRental()
        {
            return View();
        }
    }
}

TorontoRoonRentals/Views/Room/PostRoom.cshtml
@model TorontoRoonRentals.ViewModels.RoomVM

<div class="container">
    <form method="post" enctype="multipart/form-data" asp-controller="Room" asp-action="PostRoom">
        <div class="row">
            <div class="col-12">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <h2 class="pt-5 pb-5">What kind of place are you listing?</h2>

                <div class="RoomType m-1 btn btn-primary font-weight-bold" id="Room">Room</div>
                <div class="RoomType m-1 btn btn-outline-primary font-weight-bold" id="Homestay">Homestay</div>
                <div class="RoomType m-1 btn btn-outline-primary font-weight-bold" id="Apartment">Apartment</div>
                <div class="RoomType m-1 btn btn-outline-primary font-weight-bold" id="Condo">Condo</div>
                <div class="RoomType m-1 btn btn-outline-primary font-weight-bold" id="House">House</div>
                <div class="RoomType m-1 btn btn-outline-primary font-weight-bold" id="Buy_Sell">Buy/Sell</div>
                <input asp-for="Room.Type" class="d-none"/>

                <div class="form-group pt-2 pb-2">
                    <h5 class="text-secondary">Enter a title for your room</h5>
                    <input asp-for="Room.Title" class="form-control" placeholder="Enter a title" />
                    <span asp-validation-for="Room.Title" class="text-danger"></span>
                </div>
                <div class="form-group pt-2 pb-2">
                    <h5 class="text-secondary">Where is the location?</h5>
                    <div class=" ">
                        <input asp-for="Room.Address" class="form-control" id="SearchAddress" />
                        <span asp-validation-for="Room.Address" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group pt-2 pb-2">
                    <h5 class="text-secondary">Enter a price of your room</h5>
                    <input asp-for="Room.Price" class="form-control w-25" placeholder="Enter a price" />
                    <span asp-validation-for="Room.Price" class="text-danger"></span>
                </div>

                <div class="form-group" style="display:none;">
                    <input asp-for="Room.Lat" class="form-control w-25" id="Lat" />
                    <span asp-validation-for="Room.Lat" class="text-danger"></span>
                </div>

                <div class="form-group" style="display:none;">
                    <input asp-for="Room.Lng" class="form-control w-25" id="Lng" />
                    <span asp-validation-for="Room.Lng" class="text-danger"></span>
                </div>

                <div class="form-group pt-2 pb-2">
                    <h5 class="text-secondary">Enter a move-in date</h5>
                    <div class=" ">
                        <input asp-for="Room.Moveindate" class="form-control" placeholder="2019-01-01" />
                        <span asp-validation-for="Room.Moveindate" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <h2 class="pt-5 pb-5 text-body text">Add photos to your listing</h2>
                    <p class="text-secondary font-italic">Photos help guests imagine staying in your place. You can start with one and add more after you publish.</p>
                    <div class="col-md-10">
                        <input asp-for="Images" type="file" multiple="multiple" />
                    </div>
                </div>
            </div>
        </div>

        <hr />

        <div class="row pt-2 pb-2">
            <div class="col-6">
                <h5 class="text-secondary">How many bathrooms you have?</h5>
            </div>
            <div class="col-6">
                <input asp-for="Room.Bathrooms" class="form-control" />
            </div>
            <span asp-validation-for="Room.Bathrooms" class="text-danger"></span>
        </div>

        <div class="row pt-2 pb-2">
            <div class="col-6">
                <h5 class="text-secondary">Is parking allowed?</h5>
            </div>
            <div class="col-6">
                <div class="col-4 btn btn-primary font-weight-bold" id="park-no">NO</div>
                <div class="col-4 btn btn-outline-primary font-weight-bold" id="park-yes">Yes</div>
                <input asp-for="Room.IsParking" class="d-none" />
            </div>
            <span asp-validation-for="Room.IsParking" class="text-danger"></span>
        </div>

        <div class="row pt-2 pb-2">
            <div class="col-6">
                <h5 class="text-secondary">Is a pet allowed?</h5>
            </div>
            <div class="col-6">
                <div class="col-4 btn btn-primary font-weight-bold" id="pet-no">NO</div>
                <div class="col-4 btn btn-outline-primary font-weight-bold" id="pet-yes">Yes</div>
                <input asp-for="Room.IsPetFriendly" class="d-none" />
            </div>
            <span asp-validation-for="Room.IsPetFriendly" class="text-danger"></span>
        </div>

        <div class="row pt-2 pb-2">
            <div class="col-6">
                <h5 class="text-secondary">Is smoking allowed?</h5>
            </div>
            <div class="col-6">
                <div class="col-4 btn btn-primary font-weight-bold" id="smoking-no">NO</div>
                <div class="col-4 btn btn-outline-primary font-weight-bold" id="smoking-yes">Yes</div>
                <input asp-for="Room.IsSmoking" class="d-none" />
            </div>
            <span asp-validation-for="Room.IsSmoking" class="text-danger"></span>
        </div>

        <hr />

        <div class="row">
            <div class="col-12">
                <h2>What utilities do you offer?</h2>
            </div>
        </div>
        <div class="row">
            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Hydro">Hydro</div>
            <input asp-for="Utilities.HasHydro" class="d-none" />

            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Airconditioning">Air conditioning</div>
            <input asp-for="Utilities.HasAirconditioning" class="d-none" />


            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Water">Water</div>

            <input asp-for="Utilities.HasWater" class="d-none" type="checkbox" />


            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Heat">Heat</div>
            <input asp-for="Utilities.HasHeat" class="d-none" type="checkbox" />

            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Wifi">Wifi</div>

            <input asp-for="Utilities.HasWifi" class="d-none" type="checkbox" />


            <div class="m-1 btn btn-outline-primary font-weight-bold" id="TV">TV</div>
            <input asp-for="Utilities.HasTv" class="d-none" type="checkbox" />
        </div>
        <hr />
        <div class="row">
            <div class="col-12">
                <h2>What appliances do you offer?</h2>
            </div>
        </div>
        <div class="row">
            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Landuary">Landuary</div>
            <input asp-for="Appliances.HasLanduary" class="d-none" />

            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Dishwasher">Dishwasher</div>
            <input asp-for="Appliances.HasDishwasher" class="d-none" />


            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Dryer">Dryer</div>

            <input asp-for="Appliances.HasDryer" class="d-none" type="checkbox" />


            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Fridge">Fridge</div>
            <input asp-for="Appliances.HasFridge" class="d-none" type="checkbox" />

            <div class="m-1 btn btn-outline-primary font-weight-bold" id="Microwave">Microwave</div>

            <input asp-for="Appliances.HasMicrowave" class="d-none" type="checkbox" />

        </div>


        <hr />

        <div class="row">
            <div class="col-12">
                <h2 class="pt-5 pb-5">Describe your place</h2>
                <div class="form-group">
                    <div>
                        <p>Write a quick summary of your place. You can highlight what’s special about your space, the neighborhood, and how you’ll interact with guests.</p>
                    </div>
                    <div class="col-md-10">
                        <textarea asp-for="Description.MainDescription" class="form-control" rows="5" placeholder="Describe the decor, light, what's nearby, ect..."></textarea>
                        <span asp-validation-for="Description.MainDescription" class="text-danger"></span>
                    </div>
                </div>
                <hr />
                <h2 class="pt-5 pb-5">Want to add more info? (optional)</h2>
                <h5 class="text-body">Use the additional fields below to share more details.</h5>

                <div class="form-group">
                    <div>
                        <h3>Your space</h3>
                        <p>Add other details that can help set guests’ expectations for their stay.</p>
                    </div>
                    <div class="col-md-10">
                        <textarea asp-for="Description.Space" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Description.Space" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div>
                        <h3>Your availability</h3>
                        <p>Let guests know how available you’ll be during their stay. For your safety, don’t share your phone number or email until you have a confirmed reservation.</p>
                    </div>
                    <div class="col-md-10">
                        <textarea asp-for="Description.Availability" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Description.Availability" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div>
                        <h3>Your neighborhood</h3>
                        <p>
                            Share what makes your neighborhood special, like a favorite coffee shop, park, or a unique landmark.
                        </p>
                    </div>
                    <div class="col-md-10">
                        <textarea asp-for="Description.Neighborhood" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Description.Neighborhood" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div>
                        <h3>Transportation</h3>
                        <p>Add info about getting around your city or neighborhood, like nearby public transportation, driving tips, or good walking routes.</p>
                    </div>
                    <div class="col-md-10">
                        <textarea asp-for="Description.Transportation" class="form-control" rows="3"></textarea>
                        <span asp-validation-for="Description.Transportation" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>

            </div>
        </div>
    </form>
</div>
<script>
    var autocomplete;
    var place;

    function activatePlaceSearch() {
        var input = document.getElementById('SearchAddress');
        autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.addListener('place_changed', geolocate);

    }

    function geolocate() {
        place = autocomplete.getPlace();
        var geoLat = place.geometry.location.lat();
        var geoLng = place.geometry.location.lng();
        console.log(geoLat, geoLng);
        var LatBox = document.getElementById('Lat');
        var LngBox = document.getElementById('Lng');
        LatBox.value = geoLat;
        LngBox.value = geoLng;

    }

</script>

<script>
    
    $("#Room_Type").val(1);

    $(".RoomType").click(function () {
        $(".RoomType").removeClass('btn-primary');
        $(".RoomType").addClass('btn-outline-primary ');
        $(this).toggleClass('btn-outline-primary btn-primary');
    });

    $("#Room").click(function () {
        $("#Room_Type").val(1);
    });
    $("#Homestay").click(function () {
        $("#Room_Type").val(2);
    });
    $("#Apartment").click(function () {
        $("#Room_Type").val(3);
    });
    $("#Condo").click(function () {
        $("#Room_Type").val(4);
    });
    $("#House").click(function () {
        $("#Room_Type").val(5);
    });
    $("#Buy_Sell").click(function () {
        $("#Room_Type").val(6);
    });

</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDVqo5gKGiKbhNstQThOhhQQlvkDQ-ds2k&libraries=places&callback=activatePlaceSearch"></script>
<script src="~/js/postRoom.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TorontoRoonRentals/Views/Room/RoomRental.cshtml
<style>

    .container-fluid {
        padding: 0px;
        margin: 0px;
    }
</style>

<div class="container-fluid">
    <div id="root"></div>
</div>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDVqo5gKGiKbhNstQThOhhQQlvkDQ-ds2k">
    </script>

    <script crossorigin="anonymous" src="~/react/dist/bundle.js"></script>

<script>
    $(".RoomType").click(function () {
    $(".RoomType").removeClass('btn-primary');
    $(".RoomType").addClass('btn-outline-primary ');
    $(this).toggleClass('btn-outline-primary btn-primary');
        });
</script>